### ISSUE TITLE
Script not working | Asking target file

### ISSUE THREAD

**Issue by KarimGhazlaoui** [Donny-GUI/tkinter-to-customtkinter-converter#2]
Hi,

Can't use the script as for now, no matter how i call the script, it output me always the same error :

"You have to specify a target file..."

The command i use to call it is : 

python tk_to_ctk.py macvendors.py macvendors_ctk.py

Both tk_to_ctk.py and macvendors.py are in the same directory.

**Comment by Donny-GUI** [comment]
Hello there!
I updated the application interface.
use the -m flag to target multiple files

example: python tk_to_ctk.py myfile.py myfile2.py myfile3.py
