### ISSUE TITLE
how to use this 

### ISSUE THREAD

**Issue by N00BMA5T3R69** [Donny-GUI/tkinter-to-customtkinter-converter#8]
there is no guide on how to use the convertor.

maybe add some instruction on where to put the code i want to convert and where the output is going to be and what code to run so it will start the convert

**Comment by N00BMA5T3R69** [comment]
i did find how to run it but the script didn't helped me to change my code

**Comment by kingskullz1** [comment]
Can you please let me know how to use it, I am struggling as well

**Comment by Donny-GUI** [comment]
```bash
git clone https://github.com/Donny-GUI/tkinter-to-customtkinter.git
cd tkinter-to-customtkinter
python main.py
```

from the beginning this is how it should work.
